# Pensamiento Computacional con Python.

<p xmlns:cc="http://creativecommons.org/ns#" xmlns:dct="http://purl.org/dc/terms/"><a property="dct:title" rel="cc:attributionURL" href="https://github.com/repomacti/pensamiento_computacional">Pensamiento Computacional a Python</a> by <a rel="cc:attributionURL dct:creator" property="cc:attributionName" href="https://gmc.geofisica.unam.mx/luiggi">Luis Miguel de la Cruz Salas</a> is licensed under <a href="https://creativecommons.org/licenses/by-sa/4.0/?ref=chooser-v1" target="_blank" rel="license noopener noreferrer" style="display:inline-block;">CC BY-SA 4.0<img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/cc.svg?ref=chooser-v1" alt=""><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/by.svg?ref=chooser-v1" alt=""><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/sa.svg?ref=chooser-v1" alt=""></a></p> 

# Broadcasting

El *broadcasting* es un término que describe cómo es que numpy trata con arreglos de diferentes dimensiones cuando se hacen operaciones entre ellos.

La siguiente figura muestra varios tipo de *broadcasting* que se aplican en los arreglos y funciones de Numpy. 

<img src="./Broadcasting.png"  style="width: 500px;"/>

**Observación**: Los cuadros en gris tenue son usados para mostrar el concepto de *broadcasting*, pero no se reserva memoria para ellos.

In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
x = np.arange(3)
x

array([0, 1, 2])

In [4]:
y = x + 5
y

array([5, 6, 7])

In [5]:
matriz = np.ones((3,3))
matriz

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [6]:
vector = np.arange(3)
vector

array([0, 1, 2])

In [7]:
matriz + vector

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [8]:
columna = np.arange(3).reshape(3,1)
columna

array([[0],
       [1],
       [2]])

In [9]:
renglon = np.arange(3)
renglon

array([0, 1, 2])

In [10]:
columna + renglon

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [11]:
columna * renglon

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4]])

**Reglas del broadcasting**<br>

Para determinar la interacción entre dos arreglos, en Numpy se siguen las siguientes reglas:

* **Regla 1**. Si dos arreglos difieren en sus dimensiones, el *shape* del que tiene menos dimensiones es completado con unos sobre su lado izquierdo
* **Regla 2**. Si el *shape* de los dos arreglos no coincide en alguna dimensión, el arreglo con el *shape* igual a 1  se completa para que coincida con el *shape* del otro arreglo.
* **Regla 3**. Si el *shape* de los dos arreglos no coincide en alguna dimensión, pero ninguna de las dos es igual a 1 entonces se tendrá un error del estilo:

```python
ValueError: operands could not be broadcast together with shapes (4,3) (4,) 
```

## Ejemplo 1.

In [12]:
Mat = np.ones((3,2))
b = np.arange(2)
print(Mat.shape)
print(Mat)
print(b.shape)
print(b)

(3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
(2,)
[0 1]


Cuando se vaya a realizar una operación con estos dos arreglos, por la **Regla 1** lo que Numpy hará internamente es:
```
Mat.shape <--- (3,2)
b.shape   <--- (1,2)
```

Luego, por la **Regla 2** se completa la dimensión del *shape* del arreglo `b` que sea igual 1:
```
Mat.shape <--- (3,2)
b.shape   <--- (3,2)
```
De esta manera es posible realizar operaciones entre ambos arreglos:

In [13]:
Mat + b

array([[1., 2.],
       [1., 2.],
       [1., 2.]])

In [14]:
Mat * b

array([[0., 1.],
       [0., 1.],
       [0., 1.]])

## Ejemplo 2.

In [15]:
Mat = np.ones((3,1))
b = np.arange(4)
print(Mat.shape)
print(Mat)
print(b.shape)
print(b)

(3, 1)
[[1.]
 [1.]
 [1.]]
(4,)
[0 1 2 3]


Por la **Regla 1** lo que Numpy hará internamente es:
```
Mat.shape <--- (3,1)
b.shape   <--- (1,4)
```

Por la **Regla 2** se completan las dimensiones de los arreglos que sean igual 1:
```
Mat.shape <--- (3,4)
b.shape   <--- (3,4)
```
De esta manera es posible realizar operaciones entre ambos arreglos:

In [16]:
Mat + b

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

## Ejemplo 3.

In [17]:
Mat = np.ones((4,3))
b = np.arange(4)
print(Mat.shape)
print(Mat)
print(b.shape)
print(b)

(4, 3)
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
(4,)
[0 1 2 3]


Por la **Regla 1** lo que Numpy hará internamente es:
```
Mat.shape <--- (4,3)
b.shape   <--- (1,4)
```

Por la **Regla 2** se completan las dimensiones de los arreglos que sean igual 1:
```
Mat.shape <--- (4,3)
b.shape   <--- (4,4)
```
Observe que en este caso los shapes de los arreglos no coinciden, por lo que no será posible operar con ellos juntos.

In [18]:
Mat + b

ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

In [19]:
Mat.shape = (3,4)
Mat

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
Mat + b

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])